### ISSUE TITLE
Unknown authentication strategy ... in default strategy

### ISSUE THREAD

**Issue by nagyv** [hapipal/haute-couture#42]
Hi,

I've set up hapipal (following basically its default boilerplate) with `/lib/auth/strategies/jwt.js` and `/lib/auth/default.js` containing my auth strategy and making it public. When I run npm start, it works fine, but when I try to run my tests using Jest, I get the following error:

```
  ● Deployment › registers the main plugin.

    AssertionError [ERR_ASSERTION]: server.auth.default() called by haute using C:\Users\Viktor\Projects\wsb-scores-backend\lib\auth\default.js: Unknown authentication strategy jwt in default strategy

       7 |   pkg: Package,
       8 |   register: async (server, options) => {
    >  9 |     await HauteCouture.using()(server, options)
         |           ^
      10 |   }
      11 | }
      12 |

      at Object.<anonymous>.module.exports.internals.Auth._setupRoute (node_modules/hapi/lib/auth.js:167:18)
      at Object.<anonymous>.module.exports.internals.Auth.default (node_modules/hapi/lib/auth.js:76:38)
      at Object.<anonymous>.internals.callMethod (node_modules/haute/lib/index.js:147:22)
      at makeCall (node_modules/haute/lib/index.js:133:29)
      at node_modules/haute/lib/index.js:137:19
      at Object.register (lib/index.js:9:11)
      at Object.<anonymous>.internals.Server.register (node_modules/hapi/lib/server.js:434:35)
```

How could I assure that the auth strategy plugin is loaded before Auth rules are set up?

Some relevant packages:
* "hapi": "17.x.x",
* "hapi-auth-jwt2": "^8.1.0",
* "haute-couture": "3.x.x",

**Comment by nagyv** [comment]
This issue is related to  https://github.com/facebook/jest/issues/4567. I'm closing it here.
